//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitTorrent.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class psy_trance_fm_bittorrent_announces
    {
        public int id { get; set; }
        public string info_hash { get; set; }
        public string peer_id { get; set; }
        public string ip { get; set; }
        public int port { get; set; }
        public int uploaded { get; set; }
        public int downloaded { get; set; }
        public int left { get; set; }
        public string @event { get; set; }
    }
}
